// Code generated by mockery 2.7.4. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "go-server/domain"

	mock "github.com/stretchr/testify/mock"
)

// ParticipationRepository is an autogenerated mock type for the ParticipationRepository type
type ParticipationRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, participation
func (_m *ParticipationRepository) Create(ctx context.Context, participation *domain.Participation) error {
	ret := _m.Called(ctx, participation)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Participation) error); ok {
		r0 = rf(ctx, participation)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetJoinedRooms provides a mock function with given fields: ctx, userId
func (_m *ParticipationRepository) GetJoinedRooms(ctx context.Context, userId int32) ([]domain.RoomItem, error) {
	ret := _m.Called(ctx, userId)

	var r0 []domain.RoomItem
	if rf, ok := ret.Get(0).(func(context.Context, int32) []domain.RoomItem); ok {
		r0 = rf(ctx, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.RoomItem)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRoomInfo provides a mock function with given fields: ctx, roomId
func (_m *ParticipationRepository) GetRoomInfo(ctx context.Context, roomId int32) (*domain.RoomInfoResponse, error) {
	ret := _m.Called(ctx, roomId)

	var r0 *domain.RoomInfoResponse
	if rf, ok := ret.Get(0).(func(context.Context, int32) *domain.RoomInfoResponse); ok {
		r0 = rf(ctx, roomId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.RoomInfoResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, roomId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRoomMembers provides a mock function with given fields: ctx, roomId
func (_m *ParticipationRepository) GetRoomMembers(ctx context.Context, roomId int32) ([]domain.Participation, error) {
	ret := _m.Called(ctx, roomId)

	var r0 []domain.Participation
	if rf, ok := ret.Get(0).(func(context.Context, int32) []domain.Participation); ok {
		r0 = rf(ctx, roomId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Participation)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, roomId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsAdmin provides a mock function with given fields: ctx, roomId, userId
func (_m *ParticipationRepository) IsAdmin(ctx context.Context, roomId int32, userId int32) (bool, error) {
	ret := _m.Called(ctx, roomId, userId)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32) bool); ok {
		r0 = rf(ctx, roomId, userId)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int32, int32) error); ok {
		r1 = rf(ctx, roomId, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LeaveRoom provides a mock function with given fields: ctx, roomId, userId
func (_m *ParticipationRepository) LeaveRoom(ctx context.Context, roomId int32, userId int32) error {
	ret := _m.Called(ctx, roomId, userId)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32) error); ok {
		r0 = rf(ctx, roomId, userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
