version: '3.1'

services:
  backend:
    image: golang:1.16.2-alpine
    restart: always
    volumes:
      - .:/server
    working_dir: /server/go-server
    ports:
      - 5000:5000
    entrypoint: go run cmd/main.go
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql
    container_name: hermitcrab_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=hermitcrab5566
    volumes:
      - ./db/mysql-init-scripts:/docker-entrypoint-initdb.d
      #- ./db/mnt/datadir:/var/lib/mysql
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10

  mysql-adminer:
    image: adminer
    restart: always
    container_name: hermitcrab_mysql_adminer
    ports:
      - 8080:8080
    depends_on:
      mysql:
        condition: service_healthy
  
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - "8081:8080"
    volumes:
      - ./swagger.yaml:/usr/share/nginx/html/swagger/swagger.yaml
    environment:
      API_URL: swagger/swagger.yaml
    depends_on:
      mysql:
        condition: service_healthy
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    depends_on:
      mysql:
        condition: service_healthy

  # mailserver:
  #   image: docker.io/mailserver/docker-mailserver:latest
  #   hostname: mail
  #   domainname: billsgate.com
  #   container_name: mailserver
  #   ports:
  #     - "25:25"
  #     - "143:143"
  #     - "587:587"
  #     - "993:993"
  #   volumes:
  #     # - maildata:/var/mail
  #     # - mailstate:/var/mail-state
  #     # - maillogs:/var/log/mail
  #     - ./config/:/tmp/docker-mailserver/
  #   environment:
  #     - PERMIT_DOCKER=host
  #     # - ENABLE_SPAMASSASSIN=1
  #     # - SPAMASSASSIN_SPAM_TO_INBOX=1
  #     # - ENABLE_CLAMAV=1
  #     # - ENABLE_FAIL2BAN=1
  #     # - ENABLE_POSTGREY=1
  #     # - ENABLE_SASLAUTHD=0
  #     # - ONE_DIR=1
  #     # - DMS_DEBUG=0
  #   cap_add:
  #     - NET_ADMIN
  #     - SYS_PTRACE
  #   restart: always