version: '3.1'

services:
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 80:80
    restart: always

  backend:
    image: golang:1.16.2-alpine
    container_name: backend
    restart: always
    volumes:
      - .:/server
    working_dir: /server/go-server
    expose:
      - 5000
    entrypoint: go run cmd/main.go
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    platform: linux/x86_64
    image: mysql
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=hermitcrab5566
    volumes:
      - ./db/mysql-init-scripts:/docker-entrypoint-initdb.d
      #- ./db/mnt/datadir:/var/lib/mysql
    expose:
      - 3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10

  mysql-adminer:
    image: adminer
    container_name: mysql-adminer
    restart: always
    expose:
      - 8080
    depends_on:
      mysql:
        condition: service_healthy
  
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    expose:
      - 8080
    volumes:
      - ./swagger.yaml:/usr/share/nginx/html/swagger/swagger.yaml
    environment:
      API_URL: swagger/swagger.yaml
    depends_on:
      mysql:
        condition: service_healthy
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    expose:
      - 5672
      - 15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
