version: '3.1'

services:
  mysql:
    image: mysql
    container_name: hermit_crab_mysql
    environment:
      - MYSQL_USER=hermitcrab
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./db/mysql-init-scripts:/docker-entrypoint-initdb.d
      #- ./db/mnt/datadir:/var/lib/mysql
    ports:
      - 3306:3306
    #healthcheck:
    #  test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
    #  timeout: 5s
    #  retries: 10

  mysql-adminer:
    image: adminer
    restart: always
    container_name: hermit_crab_mysql_adminer
    ports:
      - 8081:8080
    #depends_on:
    #  mysql:
    #    condition: service_healthy
