openapi: 3.0.0
info:
  title: Salamander api server
  description: Salamander is the backend api server for HermitCrab.
  version: 1.0.1
servers:
- url: http://localhost:5000/api/v1
tags:
- name: users
  description: Users of HermitCrab
paths:
  /users:
    get:
      tags:
      - users
      summary: get users
      operationId: getUsers
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
                x-content-type: application/json
    post:
      tags:
      - users
      summary: create new user
      operationId: postUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
        required: true
      responses:
        "201":
          description: successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /users/{id}:
    get:
      tags:
      - users
      summary: get user by id
      operationId: getUser
      parameters:
      - name: id
        in: path
        description: User ID
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    put:
      tags:
      - users
      summary: update a user
      operationId: putUser
      parameters:
      - name: id
        in: path
        description: User ID
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      requestBody:
        description: user info to update
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
        required: true
      responses:
        "200":
          description: updated successfully
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: kevin yu
        email:
          type: string
          format: email
          example: kevin@ntu.im
        rating:
          type: integer
          example: 5
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      example:
        updated_at: 2000-01-23T04:56:07.000+00:00
        name: kevin yu
        rating: 5
        created_at: 2000-01-23T04:56:07.000+00:00
        id: 1
        email: kevin@ntu.im
    UserRequest:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
          format: email
      example:
        name: kevin yu
        email: kevin@ntu.im
