openapi: 3.0.0
info:
  title: HermitCrab api server
  description: This is a sample server of HermitCrab app.
  version: 1.0.1
servers:
- url: http://localhost:5000/api/v1
tags:
- name: users
  description: Users of HermitCrab
paths:
  /users:
    post:
      tags:
      - users
      summary: create a new user
      operationId: postUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        "201":
          description: successfully created
        "400":
          description: Missing Parameters
        "422":
          description: Usually indicates a duplicated email or unsafe password
  /users/{id}:
    get:
      tags:
      - users
      summary: get a user by id
      operationId: getUser
      parameters:
      - name: id
        in: path
        description: User ID
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        "403":
          description: not logged in
    put:
      tags:
      - users
      summary: update a user
      operationId: putUser
      parameters:
      - name: id
        in: path
        description: User ID
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      requestBody:
        description: user info to update
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        "200":
          description: updated successfully
        "403":
          description: not logged in
        "422":
          description: cannot update user with the given info
components:
  schemas:
    User:
      required:
      - email
      - id
      - name
      type: object
      properties:
        id:
          type: integer
        name:
          maxLength: 50
          type: string
          example: kevin yu
        email:
          type: string
          format: email
          example: user@example.com
        rating:
          type: integer
          example: 5
      example:
        name: kevin yu
        rating: 5
        id: 0
        email: user@example.com
  responses:
    Forbidden:
      description: not logged in
