/*
 * Salamander api server
 *
 * Salamander is the backend api server for Bills Gate.
 *
 * API version: 1.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RoomRequest struct {

	MaxCount int32 `json:"max_count"`

	AdminId int32 `json:"admin_id,omitempty"`

	ServiceId int32 `json:"service_id"`

	PlanName string `json:"plan_name"`

	IsPublic bool `json:"is_public"`

	Announcement string `json:"announcement,omitempty"`

	MatchingDeadline string `json:"matching_deadline,omitempty"`

	PublicMessage string `json:"public_message,omitempty"`
}
