/*
 * Salamander api server
 *
 * Salamander is the backend api server for HermitCrab.
 *
 * API version: 1.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type Member struct {

	UserId int32 `json:"user_id,omitempty"`

	UserName string `json:"user_name,omitempty"`

	JoinedAt time.Time `json:"joined_at,omitempty"`

	EndAt time.Time `json:"end_at,omitempty"`

	PaymentStatus *PaymentStatus `json:"payment_status,omitempty"`
}
