/*
 * Salamander api server
 *
 * Salamander is the backend api server for HermitCrab.
 *
 * API version: 1.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type Body1 struct {

	StartingTime time.Time `json:"starting_time,omitempty"`

	RoundInterval int32 `json:"round_interval,omitempty"`

	PaymentDeadline int32 `json:"payment_deadline,omitempty"`

	IsAddCalendar bool `json:"is_add_calendar,omitempty"`
}
