/*
 * Salamander api server
 *
 * Salamander is the backend api server for HermitCrab.
 *
 * API version: 1.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Admin struct {

	Name string `json:"name,omitempty"`

	Email string `json:"email,omitempty"`

	Rating int32 `json:"rating,omitempty"`

	Phone string `json:"phone,omitempty"`
}
