/*
 * Salamander api server
 *
 * Salamander is the backend api server for Bills Gate.
 *
 * API version: 1.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RoomItem struct {

	RoomId int32 `json:"room_id,omitempty"`

	ServiceName string `json:"service_name,omitempty"`

	PlanName string `json:"plan_name,omitempty"`

	IsHost bool `json:"is_host,omitempty"`

	Cost int32 `json:"cost,omitempty"`

	IsPublic bool `json:"is_public,omitempty"`

	PaymentStatus *PaymentStatus `json:"payment_status,omitempty"`

	RoomStatus *RoomStatus `json:"room_status,omitempty"`
}
