/*
 * Salamander api server
 *
 * Salamander is the backend api server for HermitCrab.
 *
 * API version: 1.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PaymentStatus string

// List of PaymentStatus
const (
	UNPAID PaymentStatus = "unpaid"
	PENDING PaymentStatus = "pending"
	CONFIRMED PaymentStatus = "confirmed"
)
