/*
 * Salamander api server
 *
 * Salamander is the backend api server for HermitCrab.
 *
 * API version: 1.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Participation struct {

	UserId int32 `json:"user_id"`

	RoomId int32 `json:"room_id"`

	IsHost bool `json:"is_host"`
}
