/*
 * HermitCrab api server
 *
 * This is a sample server of HermitCrab app.
 *
 * API version: 1.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type User struct {

	Id int32 `json:"id"`

	Name string `json:"name"`

	Email string `json:"email"`

	Rating int32 `json:"rating,omitempty"`
}
