/*
 * Salamander api server
 *
 * Salamander is the backend api server for HermitCrab.
 *
 * API version: 1.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RoomPublic struct {

	RoomId int32 `json:"room_id,omitempty"`

	Admin *Admin `json:"admin,omitempty"`

	ServiceName string `json:"service_name,omitempty"`

	PlanName string `json:"plan_name,omitempty"`

	Cost int32 `json:"cost,omitempty"`

	MaxCount int32 `json:"max_count,omitempty"`

	MemberCount int32 `json:"member_count,omitempty"`
}
