/*
 * Salamander api server
 *
 * Salamander is the backend api server for Bills Gate.
 *
 * API version: 1.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Body6 struct {

	RoomId int32 `json:"room_id,omitempty"`

	UserId int32 `json:"user_id,omitempty"`
}
