/*
 * Salamander api server
 *
 * Salamander is the backend api server for HermitCrab.
 *
 * API version: 1.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/api/v1/",
		Index,
	},

	Route{
		"SignIn",
		strings.ToUpper("Post"),
		"/api/v1/auth/signin",
		SignIn,
	},

	Route{
		"SignUp",
		strings.ToUpper("Post"),
		"/api/v1/auth/signup",
		SignUp,
	},

	Route{
		"CreateRoom",
		strings.ToUpper("Post"),
		"/api/v1/rooms",
		CreateRoom,
	},

	Route{
		"GetUser",
		strings.ToUpper("Get"),
		"/api/v1/users/{id}",
		GetUser,
	},

	Route{
		"GetUsers",
		strings.ToUpper("Get"),
		"/api/v1/users",
		GetUsers,
	},

	Route{
		"PutUser",
		strings.ToUpper("Put"),
		"/api/v1/users/{id}",
		PutUser,
	},
}
